services:
  app:
    build: .
    container_name: python-server-prod
    restart: unless-stopped
    networks:
      - web

  caddy:
    image: caddy:2
    container_name: caddy-proxy-prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./prod.Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
