services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: python-server
    networks:
      - web

  caddy:
    image: caddy:2
    container_name: caddy-proxy
    ports:
      - "8080:80"
    volumes:
      - ./dev.Caddyfile:/etc/caddy/Caddyfile
    networks:
      - web

networks:
  web:
    driver: bridge
