services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: python-server
    ports:
      - "8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - web

  caddy:
    image: caddy:2
    container_name: caddy-proxy
    ports:
      - "8080:80"
    volumes:
      - ./dev.Caddyfile:/etc/caddy/Caddyfile
    networks:
      - web

networks:
  web:
    driver: bridge
