services:
  caddy:
    build:
        dockerfile: Dockerfile
        context: .
    restart: unless-stopped
    ports:
      - "8080:80"
    command: caddy file-server --domain localhost --root /srv --listen :80
